### ISSUE TITLE
Bug - mod interaction - Not consuming input items / crash

### ISSUE THREAD

**Issue by blaaap** [Ellpeck/Wopper#2]
Pack: Modern Skyblock 1.8 hotfix
Mod version: Wopper-1.11.2-r3.jar

Sky resources mod has an item: crucible inserter. The use for this item is to automate item insertion into the crucible (from the same mod) instead of dropping items in.

When using a chest on top of a wooden hopper into the crucible inserter -> items that should get consumed into the crucible are not used up.

Not sure if this is a bug in Wopper or Sky resources, but the interaction between the mods breaks something - allowing a sort of duping/infinite resources.

doing the same setup, but replacing the crucible for a chest crashes a server with the following crashlog: 
https://pastebin.com/CXmwBAbY

Posting this here since the crucible inserter does work as intended (consuming input items) with a vanilla hopper.

**Comment by Ellpeck** [comment]
That crash is definitely related to the Sky Resources mod, and the other issue also seems to be related to it, as it doesn't seem to happen with any other machine - correct?

**Comment by blaaap** [comment]
Yeah this seems to be the case, just tested that a bit more. you can cancel this and I will report it to the Sky Resources mod as a bug.
