### ISSUE TITLE
 1.12-r4 crashes dedicated server Forge 1.12 build 2400

### ISSUE THREAD

**Issue by kreezxil** [Ellpeck/Wopper#5]
Notes:
     on startup

crash report:
https://gist.github.com/c8fff22fc57471e6aaac5463860099f6

fml server latest:
https://gist.github.com/045213b400c1c8df893ef85acfad6a80

**Comment by Darkosto** [comment]
I'm getting the same crash on Forge build 2426:

https://pastebin.com/CxwgQtcD
